// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl'], [], false);
goog.addDependency('/../../../../../../../lib/sources/controllers/basecontrol.js', ['zz.ui.mdl.controllers.BaseControl'], ['goog.events.Event', 'goog.ui.Component', 'goog.ui.Control', 'zz.i18n.services.DefaultFormatter', 'zz.models.Message', 'zz.models.enums.EventType', 'zz.ui.mdl.views.BaseView'], false);
goog.addDependency('/../../../../../../../lib/sources/views/baseview.js', ['zz.ui.mdl.views.BaseView'], ['goog.ui.ControlRenderer', 'goog.ui.registry'], false);
goog.addDependency('/../../../../../../../node_modules/zz.i18n/lib/sources/base.js', ['zz.i18n'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.i18n/lib/sources/services/basemessages.js', ['zz.i18n.services.BaseMessages'], ['goog.array', 'goog.dom', 'soy'], false);
goog.addDependency('/../../../../../../../node_modules/zz.i18n/lib/sources/services/decimalformatter.js', ['zz.i18n.services.DecimalFormatter'], ['goog.i18n.NumberFormat', 'goog.i18n.NumberFormat.Format'], false);
goog.addDependency('/../../../../../../../node_modules/zz.i18n/lib/sources/services/defaultformatter.js', ['zz.i18n.services.DefaultFormatter'], [], false);
