// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl'], [], false);
goog.addDependency('/../../../../../../../lib/sources/controllers/basecontrol.js', ['zz.ui.mdl.controllers.BaseControl'], ['goog.events.Event', 'goog.ui.Component', 'goog.ui.Control', 'zz.models.Message', 'zz.models.enums.EventType', 'zz.ui.formatter.Default', 'zz.ui.mdl.views.BaseView'], false);
goog.addDependency('/../../../../../../../lib/sources/views/baseview.js', ['zz.ui.mdl.views.BaseView'], ['goog.ui.ControlRenderer', 'goog.ui.registry'], false);
